%YAML 1.2
---
structuredData: |
    <script type="application/ld+json">
    {
      "@context": "http://schema.org",
      "@type": "BreadcrumbList",
      "itemListElement": [{
        "@type": "ListItem",
        "position": 1
        "item": {
          "@id": "$baseUrl/",
          "name": "Avvocato Dora Ballabio",
          "image": "$baseUrl/images/$logo"
        }
      },{
        "@type": "ListItem",
        "position": 2,
        "item": {
          "@id": "$baseUrl/competenze",
          "name": "Competenze",
          "image": "$baseUrl/images/$logo"
        }
      },{
        "@type": "ListItem",
        "position": 3,
        "item": {
          "@id": "$baseUrl/competenze/$page.html",
          "name": "$title",
          "image": "$baseUrl/images/$page.$iconsExt"
        }
      }]
    }
    </script>

