%YAML 1.2
---
baseUrl: https://avvocatodoraballabio.com
faviconsPrefix: ../favicons/favicon-
faviconsExtension: png
siteName: Avvocato Dora Ballabio
mail: dora.ballabio@outlook.it
mailPec: dora.ballabio@milano.pecavvocati.it
phone: "02 29516250"
cell: "+39 340 467 9375"
address: |
    Presso Studio Legale Benato<br />
    Via Monteverdi, 16<br />
    20131 - Milano (MI), Italia<br />
addressLink: https://goo.gl/maps/h83VKFeKEU62
linkedin: https://it.linkedin.com/in/dora-ballabio-48014073
logo: logo.png
logoJPEG: logo.jpeg
iconsExt: png
footer: |
    <div class="inner">
        <h2 class="major">Contatti</h2>
        <p>Per concordare un appuntamento compilare ed inviare il modulo sottostante.
        Oppure utilizzare i seguenti riferimenti.</p>
        <form method="POST" action="https://formspree.io/$mail">
            <div class="field">
                <label for="name">Name</label>
                <input type="text" name="name" id="name" />
            </div>
            <div class="field">
                <label for="email">Email</label>
                <input type="email" name="email" id="email" />
            </div>
            <div class="field">
                <label for="message">Message</label>
                <textarea name="message" id="message" rows="4"></textarea>
            </div>
            <ul class="actions">
                <li><input type="submit" value="Send Message" /></li>
            </ul>
            <input type="hidden" name="_language" value="it" />
        </form>
        <ul class="contact">
            <li class="fa-home">
                <a href="$addressLink">$address</a>
            </li>
            <li class="fa-phone"><a href="tel:$phone">$phone</a></li>
            <li class="fa-phone"><a href="tel:$cell">$cell</a></li>
            <li class="fa-envelope"><a href="mailto:$mailPec">$mailPec</a></li>
            <li class="fa-envelope"><a href="mailto:$mail">$mail</a></li>
            <li class="fa-linkedin"><a href="$linkedin">$linkedin</a></li>
        </ul>
        <ul class="copyright">
            <li>&copy; Dora Ballabio All rights reserved.</li><li>Design: <a href="http://html5up.net">HTML5 UP</a></li>
        </ul>
    </div>
